spring:
      application:
            name: starwars
      main:
            banner-mode: "off"

mongo:
      host: localhost
      name: starwars

swapi:
      url:
            planets: https://swapi.co/api/planets

management.endpoints.web.exposure.include: "*"